### ISSUE TITLE
Memory leak if SetClipboardData returns error?

### ISSUE THREAD

**Issue by idawes** [atotto/clipboard#11]
I'm not entirely familiar with the Windows API, but from the description of SetClipboardData() it appears that ownership of the memory object allocated in WriteAll() is not transferred to the system if SetClipboardData fails, so it would be up to WriteAll() to free it.

**Comment by shurcooL** [comment]
Was this resolved by #26 (it mentioned so) and should be closed, or is there more to be done?

**Comment by atotto** [comment]
That's right. closes.
Thanks!
