### ISSUE TITLE
xsel and xcopy are X11-specific, not Linux-specific

### ISSUE THREAD

**Issue by yegortimoshenko** [atotto/clipboard#12]
`xsel` and `xcopy` are both POSIX programs and run perfectly on any Unix system, including OpenBSD, NetBSD and FreeBSD. Not just Linux.

Instead of being Linux-specific, contents of `clipboard_linux.go` should be provided by default as a fallback.

**Comment by atotto** [comment]
Thank you for your suggest.

Sorry for my late reply.

This is my plan:

* mv `clipboard_linux.go` `clipboard_unix.go`
* fix the build tag:

```go
// +build freebsd linux netbsd openbsd solaris
```

BTW, I have no plan that tests under the freebsd, netbsd, openbsd and solaris... :tired_face: 

Thanks.

**Comment by atotto** [comment]
wip https://github.com/atotto/clipboard/tree/issues/12
