### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by sakhnik** [atotto/clipboard#44]
Xclip, xsel won't work properly in native Wayland applications. Could the program prefer https://github.com/bugaevc/wl-clipboard if `WAYLAND_DISPLAY` is defined?

**Comment by MichaelHipp** [comment]
Perhaps I misunderstand. On on my Ubuntu 19.04 system I'm running Wayland and clipboard worked fine once I installed wl-clipboard (sudo apt install wl-clipboard). It failed with error before that.

**Comment by sakhnik** [comment]
You're right, sorry for troubling!

**Comment by Soundtoxin** [comment]
I think the misunderstanding comes from the readme that only mentions xclip and xsel currently. Glad to know it will work on Wayland and supports wl-clipboard.
